# Mastering PyTorch Tensors: The Foundation of Deep Learning

Welcome to this concise guide on PyTorch Tensors! As the fundamental building blocks of PyTorch, understanding tensors is crucial for anyone diving into deep learning. They're like NumPy arrays but supercharged for GPUs.

Let's explore their creation, attributes, and basic operations.

In [75]:
import torch

print(f"PyTorch Version: {torch.__version__}")

PyTorch Version: 2.11.0+cpu


## 📊 Tensor Dimensions: Scalars, Vectors, Matrices, and Beyond

Tensors can have various dimensions, each representing different data structures.

### 0D Tensor (Scalar)
A scalar is a single numerical value with zero dimensions.

In [76]:
# Create a 0-dimensional tensor (scalar)
scalar = torch.tensor(7)

print(f"Scalar: {scalar}")
print(f"Dimension (ndim): {scalar.ndim}")
print(f"Shape: {scalar.shape}")

Scalar: 7
Dimension (ndim): 0
Shape: torch.Size([])


### 1D Tensor (Vector)
A vector is an ordered list of numbers, having one dimension.

In [77]:
# Create a 1-dimensional tensor (vector)
vector = torch.tensor([1, 2, 3])

print(f"Vector: {vector}")
print(f"Dimension (ndim): {vector.ndim}")
print(f"Shape: {vector.shape}")

Vector: tensor([1, 2, 3])
Dimension (ndim): 1
Shape: torch.Size([3])


### 2D Tensor (Matrix)
A matrix is a grid of numbers (rows and columns), possessing two dimensions.

In [ ]:
# Create a 2-dimensional tensor (matrix)
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

print(f"Matrix: {matrix}")
print(f"Dimension (ndim): {matrix.ndim}")
print(f"Shape: {matrix.shape}")

Matrix: tensor([[1, 2, 3],
        [4, 5, 6]])
Dimension (ndim): 2
Shape: torch.Size([2, 3])


### 3D Tensor (Cube)
A 3D tensor can be thought of as a collection of matrices or a cube of numbers, having three dimensions. For example, a color image can be represented as (Height, Width, Color Channels).

In [ ]:
# Create a 3-dimensional tensor
cube = torch.tensor([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]]])

print(f"Cube: {cube}")
print(f"Dimension (ndim): {cube.ndim}")
print(f"Shape: {cube.shape}")

# Example: Image representation (Height, Width, Color Channels)
image_tensor = torch.rand(size=(224, 224, 3))
print(f"\nExample Image Tensor Shape: {image_tensor.shape}")

Cube: tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Dimension (ndim): 3
Shape: torch.Size([2, 2, 3])

Example Image Tensor Shape: torch.Size([224, 224, 3])


## ✨ Special Tensor Creation Methods

PyTorch provides handy functions to create tensors with specific initial values.

### `torch.rand()`: Random Tensors
Generates tensors filled with random numbers (uniform distribution between 0 and 1).

In [ ]:
random_matrix = torch.rand([2, 3])
print(f"Random Matrix:\n{random_matrix}")

random_3d_tensor = torch.rand([2, 2, 2])
print(f"\nRandom 3D Tensor:\n{random_3d_tensor}")

Random Matrix:
tensor([[0.0263, 0.1678, 0.6747],
        [0.3817, 0.4487, 0.2829]])

Random 3D Tensor:
tensor([[[0.1375, 0.4912],
         [0.8869, 0.7671]],

        [[0.0236, 0.6881],
         [0.2107, 0.6314]]])


### `torch.zeros()` & `torch.ones()`
Create tensors filled entirely with zeros or ones, respectively.

In [ ]:
zeros_tensor = torch.zeros(size=(2, 2))
print(f"Zeros Tensor:\n{zeros_tensor}")

ones_tensor = torch.ones(size=(2, 2))
print(f"\nOnes Tensor:\n{ones_tensor}")

Zeros Tensor:
tensor([[0., 0.],
        [0., 0.]])

Ones Tensor:
tensor([[1., 1.],
        [1., 1.]])


### `torch.arange()`: Ranging Tensors
Creates a 1D tensor with a sequence of numbers within a specified range, with an optional step size.

In [ ]:
range_tensor = torch.arange(start=0, end=10, step=2)
print(f"Ranging Tensor (step 2): {range_tensor}")

Ranging Tensor (step 2): tensor([0, 2, 4, 6, 8])


### `torch.zeros_like()` & `torch.ones_like()`
These are super useful for creating new tensors with the *same shape and data type* as an existing tensor, but filled with zeros or ones. Great for initializing gradients!

In [ ]:
example_tensor = torch.rand(3, 4)
print(f"Original Tensor:\n{example_tensor}")

zeros_like_example = torch.zeros_like(example_tensor)
print(f"\nZeros like Original:\n{zeros_like_example}")

ones_like_example = torch.ones_like(example_tensor)
print(f"\nOnes like Original:\n{ones_like_example}")

Original Tensor:
tensor([[0.7586, 0.9104, 0.3342, 0.4285],
        [0.5882, 0.7165, 0.4392, 0.3805],
        [0.8077, 0.3663, 0.4870, 0.6205]])

Zeros like Original:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones like Original:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


## 🔍 Tensor Attributes: What Makes a Tensor Tick?

Tensors have several key attributes that define their characteristics.

In [ ]:
my_tensor = torch.rand(3, 4, dtype=torch.float32)

print(f"Tensor: {my_tensor}")
print(f"Shape: {my_tensor.shape}")       # Dimensions of the tensor
print(f"Data Type: {my_tensor.dtype}")     # Data type of elements (e.g., float32)
print(f"Number of Dimensions (ndim): {my_tensor.ndim}") # How many dimensions
print(f"Device: {my_tensor.device}")       # Where the tensor is stored (cpu or gpu)
print(f"Number of Elements: {my_tensor.numel()}") # Total number of elements

Tensor: tensor([[0.7423, 0.3398, 0.7082, 0.7600],
        [0.6666, 0.2723, 0.2429, 0.2494],
        [0.8266, 0.9488, 0.8650, 0.5207]])
Shape: torch.Size([3, 4])
Data Type: torch.float32
Number of Dimensions (ndim): 2
Device: cpu
Number of Elements: 12


### Changing Tensor Data Types
You can easily convert a tensor to a different data type.

In [ ]:
tensor_float32 = torch.tensor([1., 2., 3.], dtype=torch.float32)
print(f"Original (float32): {tensor_float32}, Dtype: {tensor_float32.dtype}")

tensor_float16 = tensor_float32.type(torch.float16)
print(f"Converted (float16): {tensor_float16}, Dtype: {tensor_float16.dtype}")

tensor_int32 = tensor_float32.type(torch.int32)
print(f"Converted (int32): {tensor_int32}, Dtype: {tensor_int32.dtype}")

Original (float32): tensor([1., 2., 3.]), Dtype: torch.float32
Converted (float16): tensor([1., 2., 3.], dtype=torch.float16), Dtype: torch.float16
Converted (int32): tensor([1, 2, 3], dtype=torch.int32), Dtype: torch.int32


## ➕ Tensor Arithmetic: Operations on Data

PyTorch tensors support all common mathematical operations, essential for neural networks.

### Basic Element-wise Operations
These operations apply to each element of the tensor.

In [ ]:
base_tensor = torch.tensor([10, 20, 30])

print(f"Original: {base_tensor}")
print(f"Add 5: {base_tensor + 5}")
print(f"Subtract 5: {base_tensor - 5}")
print(f"Multiply by 2: {base_tensor * 2}")
print(f"Divide by 2: {base_tensor / 2}")

# Or using torch functions:
print(f"\nTorch add: {torch.add(base_tensor, 5)}")
print(f"Torch subtract: {torch.sub(base_tensor, 5)}")
print(f"Torch multiply: {torch.mul(base_tensor, 2)}")

Original: tensor([10, 20, 30])
Add 5: tensor([15, 25, 35])
Subtract 5: tensor([ 5, 15, 25])
Multiply by 2: tensor([20, 40, 60])
Divide by 2: tensor([ 5., 10., 15.])

Torch add: tensor([15, 25, 35])
Torch subtract: tensor([ 5, 15, 25])
Torch multiply: tensor([20, 40, 60])


### Matrix Multiplication (`torch.matmul` or `@`)
This is a core operation in deep learning. Remember the rules: the inner dimensions must match (columns of first matrix == rows of second matrix).

In [ ]:
matrix_A = torch.tensor([[1, 2],
                         [3, 4]])
matrix_B = torch.tensor([[5, 6],
                         [7, 8]])

# Using torch.matmul()
result_matmul = torch.matmul(matrix_A, matrix_B)
print(f"Matrix A:\n{matrix_A}\n")
print(f"Matrix B:\n{matrix_B}\n")
print(f"Result (torch.matmul):\n{result_matmul}\n")

# Using the @ operator (syntactic sugar)
result_at = matrix_A @ matrix_B
print(f"Result (@ operator):\n{result_at}")

Matrix A:
tensor([[1, 2],
        [3, 4]])

Matrix B:
tensor([[5, 6],
        [7, 8]])

Result (torch.matmul):
tensor([[19, 22],
        [43, 50]])

Result (@ operator):
tensor([[19, 22],
        [43, 50]])


### Transposing a Tensor (`.T`)
Transposing flips the dimensions of a tensor, turning rows into columns and vice-versa. This is often needed to satisfy matrix multiplication requirements.

In [ ]:
tensor_original = torch.rand(2, 3) # A 2x3 tensor
print(f"Original Tensor (2x3):\n{tensor_original}\n")

tensor_transposed = tensor_original.T # Now a 3x2 tensor
print(f"Transposed Tensor (3x2):\n{tensor_transposed}\n")

# Example of using transpose for compatible matrix multiplication
matrix_X = torch.rand(2, 3) # (2x3)
matrix_Y = torch.rand(2, 3) # (2x3)

# Direct multiplication would fail: torch.matmul(matrix_X, matrix_Y)

# Transpose Y to make it (3x2)
compatible_product = torch.matmul(matrix_X, matrix_Y.T)
print(f"Matrix X (2x3):\n{matrix_X}\n")
print(f"Matrix Y (2x3):\n{matrix_Y}\n")
print(f"Product of X and Y.T (2x2):\n{compatible_product}")

Original Tensor (2x3):
tensor([[0.5988, 0.2704, 0.6388],
        [0.3748, 0.2784, 0.7944]])

Transposed Tensor (3x2):
tensor([[0.5988, 0.3748],
        [0.2704, 0.2784],
        [0.6388, 0.7944]])

Matrix X (2x3):
tensor([[0.1430, 0.9363, 0.5576],
        [0.6503, 0.4407, 0.0743]])

Matrix Y (2x3):
tensor([[0.6297, 0.5726, 0.5121],
        [0.3047, 0.0900, 0.0254]])

Product of X and Y.T (2x2):
tensor([[0.9117, 0.1420],
        [0.6999, 0.2397]])


## 📈 Aggregation: Min, Max, Mean, Sum

These operations help summarize tensor data.

In [ ]:
data_tensor = torch.arange(0, 100, 10)
print(f"Data Tensor: {data_tensor}")

print(f"Minimum Value: {torch.min(data_tensor)}") # Or data_tensor.min()
print(f"Maximum Value: {data_tensor.max()}") # Or torch.max(data_tensor)
print(f"Sum of all elements: {data_tensor.sum()}") # Or torch.sum(data_tensor)

# Mean requires float type
print(f"Mean of elements: {torch.mean(data_tensor.type(torch.float32))}")

Data Tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum Value: 0
Maximum Value: 90
Sum of all elements: 450
Mean of elements: 45.0


### Argmin & Argmax: Finding Element Indices
These functions return the *index* (position) of the minimum or maximum value in a tensor.

In [ ]:
index_tensor = torch.tensor([9, 5, 20, 1, 15])
print(f"Tensor: {index_tensor}")

print(f"Index of Min Value: {index_tensor.argmin()}") # Value is 1 at index 3
print(f"Index of Max Value: {index_tensor.argmax()}") # Value is 20 at index 2

Tensor: tensor([ 9,  5, 20,  1, 15])
Index of Min Value: 3
Index of Max Value: 2


## 🔄 Reshaping Tensors

Changing the shape of a tensor without changing its data is a common operation, especially in neural network layers.

In [ ]:
original_1d = torch.arange(1, 11)
print(f"Original 1D Tensor: {original_1d}\n")

# Reshape to a 5x2 matrix
reshaped_5x2 = original_1d.reshape(5, 2)
print(f"Reshaped to (5, 2):\n{reshaped_5x2}\n")

# Reshape to 1 row, let PyTorch infer columns (-1)
reshaped_1_row = original_1d.reshape(1, -1)
print(f"Reshaped to (1, -1):\n{reshaped_1_row}\n")

# Reshape to 2 rows, let PyTorch infer columns (-1)
reshaped_2_rows = original_1d.reshape(2, -1)
print(f"Reshaped to (2, -1):\n{reshaped_2_rows}")

Original 1D Tensor: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Reshaped to (5, 2):
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

Reshaped to (1, -1):
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

Reshaped to (2, -1):
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


## 🤝 NumPy & PyTorch Interoperability

Seamless conversion between NumPy arrays and PyTorch tensors is a powerful feature.

### NumPy Array to PyTorch Tensor
Use `torch.from_numpy()` to convert a NumPy array to a PyTorch tensor. The data types are often preserved.

In [ ]:
import numpy as np

numpy_array_example = np.arange(1., 9., dtype=np.float64)
print(f"NumPy Array: {numpy_array_example}, Dtype: {numpy_array_example.dtype}")

torch_tensor_from_numpy = torch.from_numpy(numpy_array_example)
print(f"PyTorch Tensor: {torch_tensor_from_numpy}, Dtype: {torch_tensor_from_numpy.dtype}")

NumPy Array: [1. 2. 3. 4. 5. 6. 7. 8.], Dtype: float64
PyTorch Tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64), Dtype: torch.float64


### PyTorch Tensor to NumPy Array
Use `.numpy()` method to convert a PyTorch tensor back to a NumPy array.

In [ ]:
pytorch_tensor_example = torch.ones(5)
print(f"PyTorch Tensor: {pytorch_tensor_example}, Dtype: {pytorch_tensor_example.dtype}")

numpy_array_from_torch = pytorch_tensor_example.numpy()
print(f"NumPy Array: {numpy_array_from_torch}, Dtype: {numpy_array_from_torch.dtype}")

PyTorch Tensor: tensor([1., 1., 1., 1., 1.]), Dtype: torch.float32
NumPy Array: [1. 1. 1. 1. 1.], Dtype: float32


---

## Conclusion

PyTorch tensors are incredibly versatile and form the backbone of all computations in PyTorch. Mastering these basics is a significant step towards building complex deep learning models. Keep practicing, and happy coding! 🧑‍💻